const content = [
  "Since the beginning of my time in music school, I’ve been wrestling with the push and pull between muscle memory and improvisation.",
  "On the one hand, muscle memory is necessary to even pick up an instrument and to play a single note. However, neuroscience tells us that as you practice (repeat) a motor pattern, you reinforce that neurologic muscle memory pathway, making you more likely to follow the exact same path in the future.",
  "This is an essential dilemma in learning to improvise, because improvisation depends on taking nothing for granted, soaking in the present moment and the sounds around you, imagining the sounds that the music needs in the upcoming moment, and delivering them from your soul (or universal intuitive human spirit, whatever you want to call it) in real time. So, if you’re unable to engage in this process fully because your muscle memory sabotages you, taking over and spitting out a previously practiced idea that may or may not be appropriate for the musical moment, then in my opinion you’re not truly improvising (or at least this is not improvisation at the highest level).",
  "But then this begs the question: how can you ever gain facility on your instrument if practicing sequences of notes can lead to this type of muscle memory trap that can poison an improvisation.",
  "My answer to this dilemma is to practice improvising with limitations. Create arbitrary rules for an improvisation that force you to break away from the muscle memory pathways that you are prone to fall into using your intuition alone.",
  "On piano for example, improvise, but your hands may never come within three octaves of each other. Or, improvise where the hands may never line up in rhythmic unison. Or improvise for three measures pianissimo and then for four measures fortissimo. The result will be that you’re able to practice improvising, without reinforcing stale muscle memory pathways.",
  `As I obsessed over integrating this concept into my practice on the drums, it also occurred to me that this same philosophy can be applied to my secondary “instrument,” composition. Many composers have come to the same conclusion, notably including Igor Stravinsky saying something to the effect of “ask me to write a piece for orchestra and I’ll stare at a blank page for hours, but ask me to write a piece for twelve tubas and flute and my mind is swimming with possibilities.”`,
  `So I practiced integrating limitations into my compositions as well. And as I worked more on this, I discovered that if I imposed limitations on many different aspects of a composition, that the piece would basically write itself. I also found that the more constraints I worked under, the more unique the piece would be, and ironically, the more creative I felt in composing it.`,
  `I began to codify all the limitations I could think of in a book I’m working on called “the inner spectrum of variables” (named in honor of the Tyshawn Sorey album of the same name). Eventually I realized that I could just compose the constraints, that they could become complete systems in themselves. The creative experience of making the constraints even became more interesting to me than minutia, and I found that the constraints had a much stronger impact on a given piece than the minutia as well.`,
  `I found that these constraints, when combined in heavy enough doses, essentially added up to being their own style, essentially added up to being their own genre. I found myself composing styles, composing genres, and I had found a systematic way to conceptualize them in my analysis of other pieces.`,
]

export default content;